#!/bin/bash
#
# imgupr // imgur uploader
# (c) 2012, Vid Maric // esdf

apikey=7f0214864ecf8fd7e316d5feba701eef
tmpfile=$HOME/.imguprtemp

curl -s -F "image=@$1" -F "key=$apikey" http://api.imgur.com/2/upload.xml > $tmpfile

printf "Image link: "; sed -n -e 's/.*<original>\(.*\)<\/original>.*/\1/p' $tmpfile
printf "Delete link: "; sed -n -e 's/.*<delete_page>\(.*\)<\/delete_page>.*/\1/p' $tmpfile

rm $tmpfile
